import { ICSSProperties } from "../css_types";
declare const LiBase: ICSSProperties;
declare const LiDisabled: ICSSProperties;
declare const Base: ICSSProperties;
declare const Input: ICSSProperties;
declare const InputDisabled: ICSSProperties;
declare const InputActive: ICSSProperties;
declare const Text: ICSSProperties;
declare const Title: ICSSProperties;
export { LiBase, LiDisabled, Base, Text, Input, InputDisabled, InputActive, Title };
