interface ICSSProperties {
  fontSize?: string | number ,
  display?: string,
  fontFamily?: string,
  alignItems?: string,
  backgroundColor?: string,
  color?: string,
  border?: string | number,
  borderBottom?: string,
  borderRadius?: string,
  padding?: string,
  cursor?: string,
  width?: string,
  height?: string,
  outline?: string,
  margin?: string,
  marginLeft?: string,
  marginRight?: string,
  marginTop?: string,
  marginBottom?: string,
  justifyContent?: string,
  alignContent?: string,
  flexDirection?: string,
  userSelect?: string,
  float?: string,
  listStyle?: string,
  alignSelf?: string,
  overflow?: string,
  backgroundRepeat?: string,
  background?: string,
  ":hover"?: object,
  ":focus"?: object,
  ":active"?: object,
  ":checked"?: object,
  boxSizing?: string,
  minWidth?: string,
  maxWidth?: string
  paddingLeft?: string,
  paddingRight?: string,
  paddingTop?: string,
  paddingBottom?: string
}

export {ICSSProperties};
