interface ICSSProperties {
  fontSize?: string | number ,
  display?: string,
  fontFamily?: string,
  alignItems?: string,
  backgroundColor?: string,
  color?: string,
  border?: string | number,
  borderBottom?: string,
  borderRadius?: string,
  padding?: string,
  cursor?: string,
  width?: string,
  height?: string,
  outline?: string,
  margin?: string,
  marginLeft?: string,
  marginRight?: string,
  marginTop?: string,
  marginBottom?: string,
  justifyContent?: string,
  alignContent?: string,
  flexDirection?: string,
  userSelect?: string,
  float?: string,
  listStyle?: string,
  ":hover"?: object,
  ":focus"?: object,
  ":active"?: object,
  ":checked"?: object,
}

export {ICSSProperties};
